---
title: "Halloween Sweets Analysis"
author: "Colin Scotland"
date: "29/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set up libraries;
```{r}
library(tidyverse)
library(here)
```

Set 'home' directory;
```{r}
here::here()
```

Source cleaning script;

```{r}
source("data_cleaning_scripts/halloween_candy_cleaning_script.R")
```

## 1. What is the total number of candy ratings given across three years.
## (Number of candy ratings, not the number of raters.  Don't count missing values).

```{r}
# Add an ID column to keep track after pivoting;
candy_all <- candy_all %>% 
  mutate(id = 1:nrow(candy_all), .before = "year")


candy_long <- candy_all %>% 
  pivot_longer(cols = c(-id, -year, -age, -country, -going_out))







candy_long %>% 
  
  mutate(num_ratings = if_else(value == "(?i)JOY" |
                               value == "(?i)MEH" |
                               value == "(?i)DESPAIR", 1, 0), .after = "value") %>% 
  summarise(total_ratings = sum(!is.na(num_ratings)))
  
```

There are 612266 ratings of sweets across the three years.

## 2.  